### ISSUE TITLE
Consulta 1

### ISSUE THREAD

**Issue by iris121** [PerfilAluminios/estoque#1]

**Comment by iris121** [comment]
O código que encontrei para a sua consulta foi o seguinte:

**Comment by iris121** [comment]
select produto.idproduto,fornecedor.nome_responsavel, produto.descricao,estoque.qtnde, estoque.`data` from fornecedor
inner join produto_has_fornecedor
on fornecedor.idfornecedor=produto_has_fornecedor.fornecedor_idfornecedor
inner join produto
on produto_has_fornecedor.produto_idproduto=produto.idproduto
inner join estoque
on produto.idproduto=estoque.produto_idproduto
where estoque.produto_idproduto=10
and MONTH(`Data`) = 05;

**Comment by iris121** [comment]
Contudo se forem testar terão antes que inserir dados de acordo com os requisitos que vocês colocaram na consulta

**Comment by iris121** [comment]
E foi o que eu fiz.
A consulta ficou da seguinte forma

**Comment by iris121** [comment]
![ex1](https://user-images.githubusercontent.com/31859181/30721834-44c2b46c-9f04-11e7-94ba-a272f365919b.PNG)

**Comment by iris121** [comment]
_Espero que seja o que procuram!_

**Comment by PerfilAluminios** [comment]
Muito obrigado testei e deu certo.
