### ISSUE TITLE
Insert

### ISSUE THREAD

**Issue by iris121** [PerfilAluminios/estoque#10]

**Comment by iris121** [comment]
Na tabela produto o valor é do tipo float então não poderia estar entre aspas para isso teria que ser CHAR

**Comment by PerfilAluminios** [comment]
deixe como float @iris121  te mandarei sem as aspas

insert into produto (idproduto, descricao, valor, tamanho, cor) values (1, 'mrenner0', $65.32, 20.0, 'mbygrave0');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (2, 'fgodbold1', $117.36, 6.0, 'blowis1');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (3, 'afrangleton2', $119.26, 14.5, 'csibley2');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (4, 'bkellett3', $205.33, 23.1, 'bcupitt3');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (5, 'ftunsley4', $182.83, 16.5, 'mtschirasche4');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (6, 'lsabathier5', $147.77, 2.3, 'dhearnshaw5');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (7, 'mcurling6', $225.27, 11.7, 'gattwell6');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (8, 'gfevier7', $205.26, 19.6, 'cmainds7');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (9, 'parnason8', $197.50, 8.9, 'djakel8');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (10, 'mharragin9', $189.46, 24.4, 'gfaragan9');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (11, 'alonglandsa', $150.33, 2.0, 'despya');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (12, 'ratwillb', $154.95, 12.7, 'kspurierb');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (13, 'oshellardc', $96.55, 17.4, 'bschruursc');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (14, 'bwingerd', $185.95, 9.7, 'achichgard');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (15, 'wleehanee', $247.73, 7.5, 'skolyagine');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (16, 'jraof', $132.33, 23.6, 'lthomenf');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (17, 'gpollettg', $294.96, 17.9, 'rcoastg');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (18, 'mcorrish', $215.87, 19.9, 'mlechmereh');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (19, 'ecathenodi', $79.93, 6.1, 'joakei');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (20, 'pvinckj', $257.94, 21.9, 'jdavidovicsj');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (21, 'jmccathayk', $51.67, 7.2, 'cabramamovk');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (22, 'csteckingsl', $127.56, 3.3, 'mmartinellil');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (23, 'jmccomasm', $248.87, 15.1, 'gcoxheadm');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (24, 'bwickendonn', $142.24, 12.5, 'amcindoen');
insert into produto (idproduto, descricao, valor, tamanho, cor) values (25, 'lwrightono', $214.18, 4.8, 'aguidoo');

**Comment by iris121** [comment]
Vocês se esqueceram de postar o insert da tabela fornecedor_has_produto
Por exemplo:
insert into fornecedor_has_produto values(1,1);

**Comment by iris121** [comment]
Obrigada resolvemos o problema das aspas
