### ISSUE TITLE
Modelagem

### ISSUE THREAD

**Issue by iris121** [PerfilAluminios/estoque#9]

**Comment by iris121** [comment]
Na tabela produto_has_fornecedor, a chave primaria seria a junção das duas chaves estrangeiras, essa seria a estrutura correta 
[Modelagem Banco.docx](https://github.com/PerfilAluminios/estoque/files/1311419/Modelagem.Banco.docx)

**Comment by bmarchete** [comment]
@iris121 Evite colocar arquivo docx. Copie e cole a imagem que aparece automático aqui, ou o código que é melhor.

Neste caso, sugiro fazer um print da imagem com a nova modelagem !

**Comment by PerfilAluminios** [comment]
obrigado pela correção! @iris121

**Comment by iris121** [comment]
![modelagem](https://user-images.githubusercontent.com/31859181/30553172-bf294a26-9c76-11e7-811c-429231c3238f.PNG)

**Comment by iris121** [comment]
Pessoal na modelagem acima na tabela fornecedor falta o atributo endereco que eu esqueci de colocar

**Comment by PerfilAluminios** [comment]
Tudo certo.
